apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagenimg
spec:
  replicas: 5
  selector:
    matchLabels:
      app: imagenimg
  template:
    metadata:
      labels:
        app: imagenimg
    spec:
      containers:
        - name: imagenimg
          image: vladimircard/imagenimg:1.0.0
          ports:
            - containerPort: 8080
          env: 
            - name: MONGODB_URI
              value: "mongodb+srv://admin:coderhouse123@cluster0.rvb9a.mongodb.net/"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name : login-service
spec:
  selector:
    app: imagenimg
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer